### ISSUE TITLE
CocoaPods: Unable to find a specification for `SwiftyJot`

### ISSUE THREAD

**Issue by mz-epos** [DavidLari/SwiftyJot#3]
Hi David

I don't know if you're still working on or maintaining this repo. I just wanted to let you know that using it as a Pod doesn't work, as there is no spec for it on CocoaPods.

Would you consider adding a spec to CocoaPods? Or could you add a version tag "0.1.0" to your repository? Then one could create their own spec to use it.

Thanks
Manuel

**Comment by DavidLari** [comment]
I am no longer maintaining this project. Feel free to fork/copy or whatever you want with it. Or to just use it as is, try this in your pod file:

```
pod 'SwiftyJot', :git => 'https://github.com/DavidLari/SwiftyJot.git'

**Comment by mz-epos** [comment]
Thanks for your reply.

I ended up copying and modifying the files I needed.
